CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE IF NOT EXISTS teachers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), username text UNIQUE NOT NULL, password_hash text NOT NULL, display_name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS classrooms (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), teacher_id uuid NOT NULL REFERENCES teachers(id) ON DELETE CASCADE, name text NOT NULL, code text UNIQUE NOT NULL, archived_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE classrooms ADD COLUMN IF NOT EXISTS archived_at timestamptz;
CREATE TABLE IF NOT EXISTS students (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), display_name text NOT NULL, pin_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE students ADD COLUMN IF NOT EXISTS age integer CHECK (age IS NULL OR age BETWEEN 1 AND 120);
ALTER TABLE students ADD COLUMN IF NOT EXISTS reading_level text;
CREATE TABLE IF NOT EXISTS classroom_memberships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), classroom_id uuid NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE, student_id uuid NOT NULL REFERENCES students(id) ON DELETE CASCADE, active boolean NOT NULL DEFAULT true, UNIQUE(classroom_id, student_id));
CREATE TABLE IF NOT EXISTS sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), token_hash text UNIQUE NOT NULL, role text NOT NULL CHECK(role IN ('TEACHER','STUDENT')), teacher_id uuid REFERENCES teachers(id) ON DELETE CASCADE, student_id uuid REFERENCES students(id) ON DELETE CASCADE, expires_at timestamptz NOT NULL, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS books (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, authors text[] NOT NULL, description text, cover_url text, isbns text[] NOT NULL DEFAULT '{}', page_count integer, categories text[] NOT NULL DEFAULT '{}', tags jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE books ADD COLUMN IF NOT EXISTS min_age integer;
ALTER TABLE books ADD COLUMN IF NOT EXISTS max_age integer;
ALTER TABLE books ADD COLUMN IF NOT EXISTS maturity_rating text;
ALTER TABLE books ADD COLUMN IF NOT EXISTS age_rating_source text;
ALTER TABLE books ADD COLUMN IF NOT EXISTS age_rating_url text;
ALTER TABLE books ADD COLUMN IF NOT EXISTS recommendable boolean NOT NULL DEFAULT false;
ALTER TABLE books ADD COLUMN IF NOT EXISTS embedding vector(1536);
ALTER TABLE books ADD COLUMN IF NOT EXISTS embedding_model text;
ALTER TABLE books ADD COLUMN IF NOT EXISTS embedding_hash text;
ALTER TABLE books ADD COLUMN IF NOT EXISTS metadata_updated_at timestamptz;
CREATE INDEX IF NOT EXISTS books_recommendable_idx ON books(recommendable) WHERE recommendable;
CREATE INDEX IF NOT EXISTS books_embedding_idx ON books USING ivfflat (embedding vector_cosine_ops) WITH (lists = 20);
CREATE TABLE IF NOT EXISTS book_sources (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), book_id uuid NOT NULL REFERENCES books(id) ON DELETE CASCADE, provider text NOT NULL, provider_id text NOT NULL, source_url text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(provider, provider_id));
CREATE TABLE IF NOT EXISTS catalog_import_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, status text NOT NULL CHECK(status IN ('RUNNING','SUCCEEDED','FAILED')), candidate_count integer NOT NULL, imported_count integer NOT NULL DEFAULT 0, skipped_count integer NOT NULL DEFAULT 0, duplicate_count integer NOT NULL DEFAULT 0, failed_count integer NOT NULL DEFAULT 0, details jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS student_story_profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), student_id uuid UNIQUE NOT NULL REFERENCES students(id) ON DELETE CASCADE, answers jsonb NOT NULL, dna jsonb NOT NULL, favorite text, summary text NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE student_story_profiles ADD COLUMN IF NOT EXISTS favorite text;
CREATE TABLE IF NOT EXISTS recommendation_batches (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), student_id uuid NOT NULL REFERENCES students(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS recommendation_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), batch_id uuid NOT NULL REFERENCES recommendation_batches(id) ON DELETE CASCADE, book_id uuid NOT NULL REFERENCES books(id), rank integer NOT NULL, score double precision NOT NULL, reason text NOT NULL, UNIQUE(batch_id, rank));
CREATE TABLE IF NOT EXISTS student_books (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), student_id uuid NOT NULL REFERENCES students(id) ON DELETE CASCADE, book_id uuid NOT NULL REFERENCES books(id), status text NOT NULL DEFAULT 'ACTIVE', current_page integer NOT NULL DEFAULT 0, feeling text, last_checkin_at timestamptz, selected_at timestamptz NOT NULL DEFAULT now(), switched_at timestamptz);
ALTER TABLE student_books ADD COLUMN IF NOT EXISTS switched_at timestamptz;
CREATE TABLE IF NOT EXISTS reading_checkins (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), student_book_id uuid NOT NULL REFERENCES student_books(id) ON DELETE CASCADE, page_number integer NOT NULL, feeling text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS teacher_student_notes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), teacher_id uuid NOT NULL REFERENCES teachers(id) ON DELETE CASCADE, classroom_id uuid NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE, student_id uuid NOT NULL REFERENCES students(id) ON DELETE CASCADE, body text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 2000), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS teacher_student_notes_lookup_idx ON teacher_student_notes(teacher_id, classroom_id, student_id, created_at DESC);
CREATE TABLE IF NOT EXISTS teacher_student_concern_actions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), teacher_id uuid NOT NULL REFERENCES teachers(id) ON DELETE CASCADE, classroom_id uuid NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE, student_id uuid NOT NULL REFERENCES students(id) ON DELETE CASCADE, concern_type text NOT NULL CHECK (concern_type IN ('NO_BOOK','MAY_NEED_HELP','CHECKIN_OVERDUE')), evidence_at timestamptz NOT NULL, acknowledged_at timestamptz NOT NULL DEFAULT now(), UNIQUE(teacher_id, classroom_id, student_id, concern_type));
