import bcrypt from 'bcryptjs';
import { createHash, randomBytes } from 'crypto';
import OpenAI from 'openai';
import { db, one, query } from './db';
import { normalizedTagScore, recommendationReason, studentPreferenceText, storyChoiceOptions, storyDimensions, storyQuestionnaireVersion, storyTagVocabulary } from './recommendations';
export { analyticsForTeacher, classroomAnalytics, classroomAnalyticsRanges, validClassroomAnalyticsRange, clickhouse, clickhouseHealthcheck, closeClickhouse, emitEvent, type ClassroomAnalytics, type ClassroomAnalyticsRange, type ReadingEventInput, type StudentAnalytics } from './clickhouse';
export const Role={TEACHER:'TEACHER',STUDENT:'STUDENT'} as const; export const ReadingStatus={ACTIVE:'ACTIVE',PAUSED:'PAUSED',SWITCHED:'SWITCHED',FINISHED:'FINISHED'} as const; export const Feeling={LOVING_IT:'LOVING_IT',ENJOYING:'ENJOYING',UNSURE:'UNSURE',GETTING_HARD:'GETTING_HARD'} as const;
export type Role=(typeof Role)[keyof typeof Role]; export type Feeling=(typeof Feeling)[keyof typeof Feeling]; export {db,one,query,bcrypt};
const hash=(value:string)=>createHash('sha256').update(value).digest('hex'); const required=(key:string)=>{const value=process.env[key];if(!value||value.includes('REPLACE'))throw new Error(`${key} is not configured`);return value};
export async function createSession(role:Role,id:string){const token=randomBytes(32).toString('base64url');await query("INSERT INTO sessions (token_hash,role,teacher_id,student_id,expires_at) VALUES ($1,$2,$3,$4,now()+interval '7 days')",[hash(token),role,role===Role.TEACHER?id:null,role===Role.STUDENT?id:null]);return token}
export async function revokeSession(token?:string){if(!token)return;await query('UPDATE sessions SET revoked_at=now() WHERE token_hash=$1 AND revoked_at IS NULL',[hash(token)])}
export async function sessionFromToken(token?:string){if(!token)return null;return (await query<any>('SELECT s.*,s.teacher_id AS "teacherId",s.student_id AS "studentId",t.display_name AS teacher_name,st.display_name AS student_name FROM sessions s LEFT JOIN teachers t ON t.id=s.teacher_id LEFT JOIN students st ON st.id=s.student_id WHERE s.token_hash=$1 AND s.expires_at>now() AND s.revoked_at IS NULL',[hash(token)]))[0]||null}
export async function studentLogin(code:string,pin:string){const rows=await query<any>('SELECT c.id AS classroom_id,c.teacher_id,s.id,s.display_name,s.pin_hash FROM classrooms c JOIN classroom_memberships m ON m.classroom_id=c.id AND m.active JOIN students s ON s.id=m.student_id WHERE c.code=$1 AND c.archived_at IS NULL',[code.trim().toUpperCase()]);for(const row of rows)if(await bcrypt.compare(pin,row.pin_hash))return{student:{id:row.id,displayName:row.display_name},classroom:{id:row.classroom_id,teacherId:row.teacher_id}};return null}
export const questions=[storyChoiceOptions.map(option=>option.primaryTag),['magical','real world','space/future','creepy mystery'],['brave hero','friend group','animal friend','different point of view'],['funny','fast','mysterious','meaningful'],['cliffhangers','characters','world-building','laughs'],['hard words','slow start','too many characters','no connection']];const dimensions=storyDimensions;
export function makeDna(answers:string[],favorite?:string){const choice=storyChoiceOptions[Number(answers[0])];const dna:any={...Object.fromEntries(answers.map((a,i)=>[dimensions[i],questions[i]?.[Number(a)]??a])),questionnaireVersion:storyQuestionnaireVersion,storyChoice:choice?.title,storyTags:choice?[...choice.tags]:[]};return{dna,favorite:favorite?.trim().slice(0,120)||null,summary:`You're a ${dna.tone} story explorer who wants to jump into ${choice?.title||'a great story'}, especially when there are ${dna.hook}.`}}
export function scoreBook(tags:any,dna:any){return normalizedTagScore(tags,dna)*3}
export { studentPreferenceText, storyTagVocabulary, recommendationReason, normalizedTagScore, createEmbeddings, vectorLiteral, isCurrentStoryProfile, isValidStoryAnswers, storyChoiceOptions, storyQuestionnaireVersion } from './recommendations';
const passageHelpFallback=()=>({explanation:'Try reading the sentence right before this one, then ask: who is doing what?',question:'What changed in this part?',strategy:'Circle one word you do not know and use the words around it for a clue.'});
const passageHelpSchema={type:'object',additionalProperties:false,required:['explanation','question','strategy'],properties:{explanation:{type:'string'},question:{type:'string'},strategy:{type:'string'}}} as const;
function isPassageHelp(value:unknown):value is ReturnType<typeof passageHelpFallback>{return typeof value==='object'&&value!==null&&['explanation','question','strategy'].every(key=>typeof (value as Record<string,unknown>)[key]==='string'&&(value as Record<string,string>)[key].trim().length>0)}
function logsOpenAIResponse(){return process.env.NODE_ENV!=='production'}
export async function helpWithPassage(passage:string,title:string,studentId:string){if(!process.env.OPENAI_API_KEY||process.env.OPENAI_API_KEY.includes('REPLACE'))return passageHelpFallback();const ai=new OpenAI({apiKey:required('OPENAI_API_KEY')});const model=process.env.OPENAI_MODEL||'gpt-5-mini';const response=await ai.responses.create({model,store:false,safety_identifier:hash(studentId).slice(0,32),instructions:'You help a grade 3-5 child return to a physical book. Give a short, encouraging clue that helps the child return to their physical book; never provide the answer. Fill every field in the requested schema.',input:`Book: ${title}\nShort passage: ${passage.slice(0,600)}`,text:{format:{type:'json_schema',name:'passage_help',strict:true,schema:passageHelpSchema}},max_output_tokens:1024,...(/^(gpt-5|o[1-9])/.test(model)?{reasoning:{effort:'low' as const}}:{})});const visibleOutput=response.output_text.trim();if(logsOpenAIResponse())console.debug('[helpWithPassage] OpenAI response',{status:response.status,incompleteDetails:response.incomplete_details,outputTokens:response.usage?.output_tokens,reasoningTokens:response.usage?.output_tokens_details?.reasoning_tokens,hasVisibleOutput:visibleOutput.length>0});try{const result=JSON.parse(visibleOutput);return isPassageHelp(result)?result:passageHelpFallback()}catch{return passageHelpFallback()}}
